modLoader="lowcodefml"
loaderVersion="[41,)"
license="LGPL-3.0-only"
issueTrackerURL="github.com/Apollo4O4/apollos-additional-structures/issues"
showAsResourcePack=false

[[mods]]
  modId="apollo"
  version="1.2"
  displayName="Apollo's Additional Structures"
  displayURL="github.com/Apollo4O4/apollos-additional-structures"
  logoFile="pack.png"
  authors="Apollo404"
  description='''
  Adds some new ambient structures into your Minecraft world!
  '''

  [[dependencies.apollo]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"

  [[dependencies.apollo]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"